services:
  ecs-local-endpoints:
    image: amazon/amazon-ecs-local-container-endpoints
    environment:
      AWS_VAULT: ${AWS_VAULT}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN}
      AWS_SESSION_EXPIRATION: ${AWS_SESSION_EXPIRATION}
    networks:
      credentials_network:
        # This special IP address is recognized by the AWS SDKs and AWS CLI
        ipv4_address: 169.254.170.2

  server:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - ecs-local-endpoints
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
    networks:
      credentials_network:

volumes:
  localstack_data:

networks:
  # This special network is configured so that the local metadata
  # service can bind to the specific IP address that ECS uses
  # in production
  credentials_network:
    driver: bridge
    ipam:
      config:
        - subnet: 169.254.170.0/24
          gateway: 169.254.170.1
