# Generated by Django 5.1 on 2024-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="filesize",
            field=models.IntegerField(default=0),
        ),
    ]
