# Generated by Django 5.1 on 2024-09-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_filesize"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="file",
            field=models.FileField(default="", upload_to="movies/"),
        ),
    ]
