# Generated by Django 5.1 on 2024-09-14 15:50

import django_example.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="file",
            field=models.FileField(
                default="",
                storage=django_example.storage_backends.PrivateMediaStorage(),
                upload_to="movies/",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="filename",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="width",
            field=models.IntegerField(default=0),
        ),
    ]
